import { makeEnum } from "../util";


export const JsonDefTypes = makeEnum(
    'NullKeyword',
    'AnyKeyword',
    'BooleanKeyword',
    'ThisKeyword',
    'RootKeyword',
    'IntegerKeyword',
    'NumberKeyword',
    'RecordKeyword',
    'ModelKeyword',
    'GroupKeyword',
    'SelectKeyword',
    'OfKeyword',
    'StringKeyword',
    'DatetimeKeyword',
    'DateKeyword',
    'TimeKeyword',
    'UuidKeyword',
    'Base64Keyword',
    'EmailKeyword',
    'TrueKeyword',
    'FalseKeyword',
    'RequiredIs',
    'OptionalIs',
    ['GenericOpen', 'LessThan'],
    ['GenericClose', 'GreaterThan'],
    'GreaterThanOrEqual',
    'LessThanOrEqual',
    'And',
    'Or',
    'Exactly',
    'Open',
    'Close',
    'ArrayOpen',
    'ArrayClose',
    'ObjectOpen',
    'ObjectClose',
    'Comma',
    'Rest',
    'Identifier',
    'Number',
    'Integer',
    'Real',
    'String',
    'Regex',
    'Eof',
    'Invalid',
    'InvalidReal',
    'InvalidString',
    'InvalidRegex',
);
