import { makeEnum } from "../util";


export const JsondefTypes = makeEnum(
    'NullToken',
    'AnyToken',
    'BooleanToken',
    'ThisToken',
    'RootToken',
    'IntegerToken',
    'NumberToken',
    'RecordToken',
    'ModelToken',
    'GroupToken',
    'SelectToken',
    'OfToken',
    'StringToken',
    'DatetimeToken',
    'DateToken',
    'TimeToken',
    'UuidToken',
    'Base64Token',
    'EmailToken',
    'RequiredIs',
    'OptionalIs',
    'GreaterThanOrEqual',
    'LessThanOrEqual',
    ['GenericOpen', 'LessThan'],
    ['GenericClose', 'GreaterThan'],
    'TrueToken',
    'FalseToken',
    'Or',
    'Exactly',
    'Open',
    'Close',
    'ArrayOpen',
    'ArrayClose',
    'ObjectOpen',
    'ObjectClose',
    'Comma',
    'Rest',
    'Identifier',
    'Number',
    'Integer',
    'Real',
    'String',
    'Escape',
    'Regex',
    'RegexBody',
    'RegexEscape',
    'Eof'
);
